### PR TITLE
Update for python3 IDA Pro > 7.0

### PR DESCRIPTION
**Pull request by nyx0**

### CODE REVIEW

**Comment by JusticeRage** [comment]
Hi!
If I understand correctly, your patch breaks compatibility with IDA < 7, is that correct? I personnally believe older versions of the applications should still be supported.
It also seems to me that your proposed changes make the whole script incompatible with Python 2, which is probably still widespread.

**Comment by mrexodia** [comment]
Yeah if the plugin doesn’t work on IDA 7 the idea is to hack around until it works for all IDA versions.

**Comment by nyx0** [comment]
Hello!
Exact, the patch breaks the compatibility with everything which is not IDA > 7
and python3 (which are mainly from IDA 7.4 if i'm not mistaken).
Sorry for that, i was thinking about making it works on the latest version and
getting rid of former artefacts.

**Comment by mrexodia** [comment]
From the looks of it a minimal update to support 7.4 and python 3 together with python 2, but I don’t really have a good view on things...

**Comment by nyx0** [comment]
Hum actually I think it should be working with IDA 7.4 and Python2.

**Comment by mrexodia** [comment]
I checked and it appears that the PR that 'adds' 7.4 support also removes support for 6.x altogether, so I guess I can merge this.

The ideal plugin would be: works from IDA 6.1 (with python 2.7 IDAPython) up to the latest IDA 7.4.

I checked and it seems that most of the code should work, but I don't care enough about IDA to maintain this.

**Pull request merged**
